# Generated by Django 5.0.6 on 2024-05-16 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
