[site]
static_dir = "static/"
templates_dir = "templates/"
content_dir = "content/"
build_dir = "output/"
base_url = "http://localhost"

[params]
description = ""
copyright = ""
keywords = ["developer", "python"]

[params.author]
name = "Daniel"
contact_email = "contact@dnlzrgz.com"

mastodon_account = "https://mastodon.social/@dnlzrgz"
fediverse_creator = "@dnlzrgz@mastodon.social"

github = "https://github.com/dnlzrgz"
linkedin = "https://www.linkedin.com/in/daniel-zaragoza-4395b4260/"
mastodon = "https://mastodon.social/@dnlzrgz"
