# Generated by Django 5.0.6 on 2024-05-26 14:15

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
    ]
