# Generated by Django 5.1 on 2024-08-27 09:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpostpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 0), ('quote', 1), ('paragraph', 2), ('code', 4), ('image', 5), ('embed', 6)], block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.blocks.BlockQuoteBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {'editor': 'full'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('CSS', 'css'), ('Go', 'Golang'), ('HTML', 'html'), ('JavaScript', 'js'), ('Python', 'py'), ('SQL', 'sql')]}), 4: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 0)]], {'label': 'Code'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.embeds.blocks.EmbedBlock', (), {})}),
        ),
    ]
