# Generated by Django 5.1.3 on 2024-11-20 10:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpostpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 0), ('quote', 1), ('paragraph', 2), ('code', 4), ('image', 5), ('embed', 6)], block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.blocks.BlockQuoteBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'bash'), ('c', 'c'), ('css', 'css'), ('django', 'django'), ('go', 'golang'), ('html', 'html'), ('java', 'java'), ('javascript', 'javascript'), ('json', 'json'), ('makefile', 'makefile'), ('markdown', 'markdown'), ('nginx', 'nginx'), ('php', 'php'), ('plaintext', 'plaintext'), ('python', 'python'), ('rust', 'rust'), ('sql', 'sql'), ('yaml', 'yaml'), ('zsh', 'zsh')]}), 4: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 0)]], {'label': 'Code'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.embeds.blocks.EmbedBlock', (), {})}),
        ),
    ]
