# Generated by Django 5.1.3 on 2024-11-21 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpostpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Post date'),
        ),
    ]
