# Generated by Django 5.0.6 on 2024-05-15 15:43

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blog_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_overtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_overtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_posts',
            field=wagtail.fields.StreamField([('post', wagtail.blocks.PageChooserBlock(page_type=['blog.BlogPostPage']))], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_projects',
            field=wagtail.fields.StreamField([('project', wagtail.blocks.PageChooserBlock(page_type=['projects.ProjectPage']))], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_overtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects_overtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
