# Generated by Django 5.0.6 on 2024-05-17 10:35

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_blog_content_homepage_blog_overtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bio_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bio_overtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bio_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
