# Generated by Django 5.0.6 on 2024-05-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_bio_content_homepage_bio_overtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
