# Generated by Django 5.0.7 on 2024-08-05 10:29

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='bio_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='bio_overtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='bio_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blog_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blog_overtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blog_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='contact_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='contact_overtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='contact_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_posts',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_overtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='projects_overtitle',
        ),
        migrations.AddField(
            model_name='homepage',
            name='biography',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stack_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stack_stack',
            field=wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stack_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
