# Generated by Django 5.1 on 2024-08-07 14:49

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_bio_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_cta',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
