# Generated by Django 5.1 on 2024-08-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_contact_content_homepage_contact_cta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='contact_text',
            new_name='contact_subtitle',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='projects_content',
            new_name='projects_subtitle',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='stack_content',
            new_name='stack_subtitle',
        ),
    ]
