# Generated by Django 5.0.6 on 2024-05-14 16:26

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy', models.CharField(blank=True, max_length=255)),
                ('links', wagtail.fields.StreamField([('url', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock())]))], blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
