# Generated by Django 5.0.8 on 2024-08-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contactemailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
