# Generated by Django 5.0.8 on 2024-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_footersettings_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
