# Generated by Django 5.1.2 on 2024-10-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_footertextsettings_sitesettings_socialmediasettings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactEmailSettings',
        ),
        migrations.DeleteModel(
            name='FooterTextSettings',
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
