# Generated by Django 5.1.2 on 2024-10-31 14:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_contactemailsettings_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('widgets', wagtail.fields.StreamField([('abstract', 0), ('calendar', 0), ('contact_email', 0), ('featured_blog_post', 3), ('featured_project', 5), ('image', 7), ('note', 9), ('social_media_links', 15), ('stack_list', 18), ('todo_list', 22)], blank=True, block_lookup={0: ('wagtail.blocks.StructBlock', [[]], {}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blog.BlogPostPage'], 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('blog_post', 2)]], {}), 4: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['projects.ProjectPage'], 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('title', 1), ('project', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.StructBlock', [[('image', 6), ('caption', 1)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 1), ('content', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 20}), 11: ('wagtail.blocks.CharBlock', (), {}), 12: ('wagtail.blocks.URLBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 11), ('url', 12)]], {'label': 'links'}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('title', 10), ('links', 14)]], {}), 16: ('wagtail.blocks.StructBlock', [[('Item', 1)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Stack items'}), 18: ('wagtail.blocks.StructBlock', [[('stack_items', 17)]], {}), 19: ('wagtail.blocks.BooleanBlock', (), {}), 20: ('wagtail.blocks.StructBlock', [[('done', 19), ('label', 1)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'label': 'Defaul tasks'}), 22: ('wagtail.blocks.StructBlock', [[('default_tasks', 21)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
