# Generated by Django 5.1.3 on 2024-11-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_homepage_widgets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactemailsettings',
            options={'verbose_name': 'Contact email'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fediverse_handle',
            field=models.CharField(blank=True, help_text='Your hanlde on the fediverse (e.g., @username@instance).', max_length=255, verbose_name='Fediverse handle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mastodon_verification',
            field=models.URLField(blank=True, help_text='Link to your Mastodon profile for verification.', verbose_name='Mastodon verification URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='title_suffix',
            field=models.CharField(blank=True, help_text="The suffix for the title meta tag e.g. ' | dnlzrgz'", max_length=255, verbose_name='Title suffix'),
        ),
    ]
