# Generated by Django 5.1.3 on 2024-11-27 09:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_homepage_widgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='widgets',
            field=wagtail.fields.StreamField([('abstract', 0), ('calendar', 0), ('contact_email', 0), ('featured_blog_post', 3), ('featured_project', 5), ('image', 8), ('note', 10), ('social_media_links', 15), ('stack_list', 18), ('todo_list', 22)], blank=True, block_lookup={0: ('wagtail.blocks.StructBlock', [[]], {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blog.BlogPostPage'], 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('blog_post', 2)]], {}), 4: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['projects.ProjectPage'], 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('title', 1), ('project', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.StructBlock', [[('image', 6), ('caption', 7)]], {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'link']}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('content', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 20}), 12: ('wagtail.blocks.URLBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 1), ('url', 12)]], {'label': 'links'}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('title', 11), ('links', 14)]], {}), 16: ('wagtail.blocks.StructBlock', [[('Item', 7)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Stack items'}), 18: ('wagtail.blocks.StructBlock', [[('stack_items', 17)]], {}), 19: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('done', 19), ('label', 7)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'label': 'Defaul tasks'}), 22: ('wagtail.blocks.StructBlock', [[('default_tasks', 21)]], {})}),
        ),
    ]
